apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: psn-application
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: psn-repository
  path: ./k8s/base
  prune: true
  wait: true
  targetNamespace: psn
