apiVersion: apps/v1
kind: Deployment
metadata:
  name: psn-exporter
  labels:
    app: psn-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psn-exporter
  template:
    metadata:
      labels:
        app: psn-exporter
    spec:
      serviceAccountName: psn-exporter
      containers:
      - name: exporter
        image: ghcr.io/sai7teja/psn-exporter:latest # This will be overridden by Kustomize/CI
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        env:
          - name: PSN_TOKEN
            valueFrom:
              secretKeyRef:
                name: psn-credentials
                key: PSN_TOKEN
          - name: GRAFANA_URL
            valueFrom:
              secretKeyRef:
                name: grafana-credentials
                key: GRAFANA_URL
          - name: GRAFANA_API_KEY
            valueFrom:
              secretKeyRef:
                name: grafana-credentials
                key: GRAFANA_API_KEY
        envFrom:
        # 1. Pulls non-sensitive URLs from the ConfigMap (auto-generated from settings.env)
        - configMapRef:
            name: psn-config
        # 2. Pulls sensitive tokens from the CSI-generated Secrets
        - secretRef:
            name: gcp-secrets
        - secretRef:
            name: vault-secrets
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: psn-exporter
