apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: psn

resources:
- deployment.yaml

# Automatically generates a ConfigMap from settings.env
# It appends a hash to the name, forcing a pod restart if you change the URL!
configMapGenerator:
- envs:
  - settings.env
  name: psn-config

# The CI pipeline will automatically update the newTag here during builds
images:
- name: ghcr.io/sai7teja/psn-exporter
  newName: ghcr.io/sai7teja/psn-exporter
  newTag: b0c49094737f640a85c8e8d744a0edf57fb9426a
