apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-provider
spec:
  provider: vault
  parameters:
    roleName: "psn-role"
    vaultAddress: "http://vault.vault.svc.cluster.local:8200"
    objects: |
      - objectName: "grafana-token"
        secretPath: "secret/data/grafana-token"
        secretKey: "token"
  secretObjects:
    - secretName: vault-secrets
      type: Opaque
      data:
        - objectName: "grafana-token"
          key: GRAFANA_API_KEY
